### PR TITLE
Switched to declarative fetching, shifted notebook.js dep outside of dom-module

### PR DESCRIPTION
**Pull request by H-Plus-Time**

### CODE REVIEW

**Comment by sbeleidy** [comment]
Hi @H-Plus-Time , thank you so much for your suggestion! I definitely agree with switching to use iron-ajax. I tried to run your code but it didn't work for me. 

I think you need to `bower install iron-ajax --save` as well as add an import under jupyter-notebook.

The only issue is that now error states keep the spinner running. What would you recommend about that? Should it just show an error message with no ability to retry since that isn't doable anymore?

Could you also please delete the commented code? I think you can also remove the attached function entirely.

Thanks again!

**Comment by sbeleidy** [comment]
Thanks for the update but it doesn't seem to be working now. This is how the demo displays for me:

screen shot 2016-12-12 at 10 25 43 pm


I also think now it's a little confusing having two properties error and err. Maybe we can switch to `error` which is the error object returned from iron-ajax and `displayError` which would be the boolean to use to display the error message. We can then make `displayError` a computed property based on `error` using a function like `_computeDisplayError(error)`. 

Let me know what you think and thank you so much for taking the time to update this.

**Comment by H-Plus-Time** [comment]
Oh dear :S. Agreed re the point about error disambiguation (they are a little too similar at the moment).

Well, looks like it was a missing import :-/.

I've added a bit of differentiation between request-based errors (404s and such) and processing/parsing errors. That should cover all the corner cases, and make things a bit clearer.

**Comment by sbeleidy** [comment]
This looks great! Thank you so much for the contribution!

**Pull request merged**
